[test]
preload = ["./test/setup.ts"]
coverageSkipTestFiles = true
coverageReporter = ["text"]
coveragePathIgnorePatterns = ["test/**", "scripts/**"]

[test.coverageThreshold]
lines = 0.90
functions = 0.90
